import type { Risk } from "./types.ts";

/**
 * Risk flagging runs inside the scan traversal because the bytes are already in
 * hand. Every downstream consumer — bundling, the wiki, the agent's write
 * approval prompt — inherits the result without paying for another pass.
 *
 * The bias throughout is toward precision over recall. A flag on ordinary source
 * trains the reader to ignore flags, which is worse than missing one.
 */

const PRIVATE_KEY_CONTENT = [
	/-----BEGIN (?:RSA |DSA |EC |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY-----/,
	/PuTTY-User-Key-File-\d/,
];

const PRIVATE_KEY_FILENAMES = new Set([
	"id_rsa",
	"id_dsa",
	"id_ecdsa",
	"id_ed25519",
	"identity",
	"server.key",
	"privkey.pem",
]);

const PRIVATE_KEY_EXTENSIONS = new Set([".pem", ".key", ".p12", ".pfx", ".jks", ".keystore"]);

const CREDENTIAL_FILENAMES = new Set([
	"credentials",
	"credentials.json",
	"secrets.json",
	"secrets.yaml",
	"secrets.yml",
	".npmrc",
	".pypirc",
	".netrc",
	"_netrc",
	".htpasswd",
]);

/** Suffixes that mark an env file as a documented template rather than a real one. */
const ENV_TEMPLATE_SUFFIXES = [".example", ".sample", ".template", ".dist", ".defaults"];

/**
 * Provider token shapes. Each of these is specific enough that a match is
 * effectively never a coincidence.
 */
const CREDENTIAL_CONTENT = [
	/\bAKIA[0-9A-Z]{16}\b/, // AWS access key id
	/\bASIA[0-9A-Z]{16}\b/, // AWS temporary access key id
	/\bgh[pousr]_[A-Za-z0-9]{36,}\b/, // GitHub token
	/\bxox[baprs]-[A-Za-z0-9-]{10,}/, // Slack token
	/\bAIza[0-9A-Za-z_-]{35}\b/, // Google API key
	/\bsk_live_[0-9a-zA-Z]{24,}\b/, // Stripe live secret
	/\bsk-ant-[A-Za-z0-9_-]{20,}/, // Anthropic
	/\bglpat-[A-Za-z0-9_-]{20,}\b/, // GitLab PAT
	/\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/, // JWT
];

/**
 * The generic rule: a secret-ish name assigned a high-entropy literal. This is
 * the only pattern that could plausibly fire on real source, so it is fenced by
 * a placeholder check and an entropy floor.
 */
const GENERIC_SECRET =
	/\b(?:password|passwd|secret|secret_key|token|auth_token|api[_-]?key|access[_-]?key|private[_-]?key|client[_-]?secret)\b\s*[:=]\s*["'`]([^"'`\n]{20,})["'`]/i;

/** Words that mark a literal as documentation rather than a live credential. */
const PLACEHOLDER_WORDS = [
	"example",
	"sample",
	"placeholder",
	"dummy",
	"fake",
	"test",
	"changeme",
	"change_me",
	"your",
	"xxxx",
	"redacted",
	"insert",
	"todo",
	"replace",
	"notreal",
	"secretsecret",
];

const GENERATED_PATH_SEGMENTS = [
	"dist/",
	"build/",
	"out/",
	".next/",
	"coverage/",
	"__generated__/",
	"generated/",
	".output/",
];

const GENERATED_FILENAME = [
	/\.min\.(?:js|css|mjs)$/,
	/\.(?:js|css|mjs)\.map$/,
	/\.pb\.go$/,
	/_pb2\.pyi?$/,
	/\.pb\.cc$/,
	/\.g\.dart$/,
	/\.generated\.[A-Za-z0-9]+$/,
	/\.designer\.cs$/i,
];

const GENERATED_CONTENT = [
	/Code generated by .+ DO NOT EDIT/i,
	/@generated\b/,
	/DO NOT EDIT(?:[.!]| THIS FILE)/i,
	/This file (?:was|is) (?:auto[- ]?)?generated/i,
	/Autogenerated by/i,
];

const LOCKFILES = new Set([
	"package-lock.json",
	"npm-shrinkwrap.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"bun.lock",
	"bun.lockb",
	"go.sum",
	"cargo.lock",
	"poetry.lock",
	"pdm.lock",
	"uv.lock",
	"gemfile.lock",
	"composer.lock",
	"pubspec.lock",
	"packages.lock.json",
	"mix.lock",
	"flake.lock",
]);

export interface RiskInput {
	/** Repo-relative POSIX path. */
	path: string;
	size: number;
	binary: boolean;
	/** Head of the file, decoded as UTF-8. Empty for binary files. */
	text: string;
	largeBinaryBytes: number;
}

export function classifyRisk(input: RiskInput): Risk[] {
	const risk = new Set<Risk>();
	const base = basename(input.path).toLowerCase();
	const ext = extname(base);

	if (LOCKFILES.has(base)) risk.add("lockfile");

	if (input.binary && input.size >= input.largeBinaryBytes) risk.add("large_binary");

	// A .pem or .key extension is only a hint about what the file *might* hold.
	// Since the content is already in hand, use it: a bundle of public
	// certificate roots is not a private key, and flagging it teaches the reader
	// to ignore the flag on the file that really is one.
	if (PRIVATE_KEY_FILENAMES.has(base) || PRIVATE_KEY_EXTENSIONS.has(ext)) {
		if (!input.binary && input.text && isCertificateOnly(input.text)) {
			// Nothing: the content settles it.
		} else {
			risk.add("private_key");
		}
	}

	if (isCredentialFilename(base)) risk.add("credentials");

	if (isGeneratedPath(input.path) || GENERATED_FILENAME.some((re) => re.test(base))) {
		risk.add("generated");
	}

	// Content rules only apply to text. Scanning binary for these is noise.
	if (!input.binary && input.text) {
		if (PRIVATE_KEY_CONTENT.some((re) => re.test(input.text))) risk.add("private_key");
		if (hasCredentialContent(input.text)) risk.add("credentials");
		if (hasGeneratedBanner(input.text)) risk.add("generated");
	}

	return [...risk].sort();
}

/**
 * PEM content that holds certificates and nothing secret. Public roots ship in
 * plenty of repositories and are not a finding.
 */
function isCertificateOnly(text: string): boolean {
	if (PRIVATE_KEY_CONTENT.some((re) => re.test(text))) return false;
	return /-----BEGIN (?:TRUSTED )?CERTIFICATE(?: REQUEST)?-----/.test(text);
}

function isCredentialFilename(base: string): boolean {
	if (CREDENTIAL_FILENAMES.has(base)) return true;
	if (base.startsWith("service-account") && base.endsWith(".json")) return true;
	if (base === ".env" || base.startsWith(".env.")) {
		// `.env.example` documents the shape; it is not a credential.
		return !ENV_TEMPLATE_SUFFIXES.some((suffix) => base.endsWith(suffix));
	}
	return false;
}

function isGeneratedPath(path: string): boolean {
	const withSlash = `${path}`;
	return GENERATED_PATH_SEGMENTS.some(
		(seg) => withSlash.startsWith(seg) || withSlash.includes(`/${seg}`),
	);
}

/** Only the first lines count — a banner buried on line 900 is not a banner. */
function hasGeneratedBanner(text: string): boolean {
	const head = firstLines(text, 40);
	return GENERATED_CONTENT.some((re) => re.test(head));
}

export function hasCredentialContent(text: string): boolean {
	if (CREDENTIAL_CONTENT.some((re) => re.test(text))) return true;

	const match = GENERIC_SECRET.exec(text);
	if (!match) return false;
	const value = match[1];
	return value !== undefined && looksLikeLiveSecret(value);
}

/**
 * The entropy floor. A live secret mixes character classes and is not a word a
 * human wrote as an illustration.
 */
export function looksLikeLiveSecret(value: string): boolean {
	if (value.length < 20) return false;

	// Interpolation and env lookups are references, not secrets.
	if (/\$\{|\$\(|process\.env|os\.environ|ENV\[|getenv|System\.getenv/.test(value)) return false;

	const lowered = value.toLowerCase();
	if (PLACEHOLDER_WORDS.some((word) => lowered.includes(word))) return false;

	// Repeated filler such as "aaaaaaaa..." or "0000...".
	if (/^(.)\1+$/.test(value)) return false;

	const hasLower = /[a-z]/.test(value);
	const hasUpper = /[A-Z]/.test(value);
	const hasDigit = /\d/.test(value);
	const classes = Number(hasLower) + Number(hasUpper) + Number(hasDigit);

	// Two classes is the floor: "abcdefghijklmnop1234" qualifies, an English
	// sentence in a config string does not.
	if (classes < 2) return false;

	// A value made of dictionary-ish words separated by spaces is prose.
	if (/\s/.test(value)) return false;

	return true;
}

export function isBinary(head: Buffer): boolean {
	return head.includes(0);
}

function firstLines(text: string, count: number): string {
	let index = 0;
	for (let i = 0; i < count; i++) {
		const next = text.indexOf("\n", index);
		if (next === -1) return text;
		index = next + 1;
	}
	return text.slice(0, index);
}

function basename(path: string): string {
	return path.slice(path.lastIndexOf("/") + 1);
}

function extname(base: string): string {
	const dot = base.lastIndexOf(".");
	return dot <= 0 ? "" : base.slice(dot);
}
