import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
	detectCommands,
	detectPackageManager,
	VERIFY_CONFIG,
} from "../src/index.ts";

const roots: string[] = [];

afterEach(async () => {
	await Promise.all(roots.splice(0).map((r) => rm(r, { recursive: true, force: true })));
});

async function repo(files: Record<string, string>): Promise<string> {
	const root = await mkdtemp(join(tmpdir(), "kaioken-detect-"));
	roots.push(root);
	for (const [path, content] of Object.entries(files)) {
		const abs = join(root, path);
		await mkdir(dirname(abs), { recursive: true });
		await writeFile(abs, content, "utf8");
	}
	return root;
}

describe("detectPackageManager", () => {
	it("detects pnpm via pnpm-lock.yaml or pnpm-workspace.yaml", async () => {
		const r1 = await repo({ "pnpm-lock.yaml": "lockfileVersion: 5.4" });
		expect(await detectPackageManager(r1)).toBe("pnpm");

		const r2 = await repo({ "pnpm-workspace.yaml": "packages:\n  - 'packages/*'" });
		expect(await detectPackageManager(r2)).toBe("pnpm");
	});

	it("detects yarn via yarn.lock", async () => {
		const r = await repo({ "yarn.lock": "# THIS IS AN AUTOGENERATED FILE." });
		expect(await detectPackageManager(r)).toBe("yarn");
	});

	it("detects bun via bun.lockb or modern bun.lock", async () => {
		const r1 = await repo({ "bun.lockb": "" });
		expect(await detectPackageManager(r1)).toBe("bun");

		const r2 = await repo({ "bun.lock": "lockfile" });
		expect(await detectPackageManager(r2)).toBe("bun");
	});

	it("detects deno via deno.json or deno.lock", async () => {
		const r1 = await repo({ "deno.json": "{}" });
		expect(await detectPackageManager(r1)).toBe("deno");

		const r2 = await repo({ "deno.lock": "{}" });
		expect(await detectPackageManager(r2)).toBe("deno");
	});

	it("defaults to npm when no lockfile is present", async () => {
		const r = await repo({ "package.json": "{}" });
		expect(await detectPackageManager(r)).toBe("npm");
	});
});

describe("MultiRuntimeDetector (detectCommands)", () => {
	it("detects Node scripts in order: typecheck, lint, build, test", async () => {
		const r = await repo({
			"package.json": JSON.stringify({
				scripts: {
					test: "vitest run",
					lint: "eslint .",
					build: "tsc",
					typecheck: "tsc --noEmit",
				},
			}),
		});

		const res = await detectCommands(r);
		expect(res.runtime).toBe("node");
		expect(res.commands.map((c) => c.label)).toEqual(["typecheck", "lint", "build", "test"]);
		expect(res.commands[0]?.command).toBe("npm run typecheck");
		expect(res.commands[1]?.command).toBe("npm run lint");
		expect(res.commands[2]?.command).toBe("npm run build");
		expect(res.commands[3]?.command).toBe("npm run test");
	});

	it("detects monorepos and falls back to workspace test commands", async () => {
		const npmMono = await repo({
			"package.json": JSON.stringify({
				workspaces: ["packages/*"],
			}),
		});
		const npmRes = await detectCommands(npmMono);
		expect(npmRes.commands.map((c) => c.command)).toEqual(["npm test --workspaces --if-present"]);

		const pnpmMono = await repo({
			"pnpm-workspace.yaml": "packages:\n  - 'packages/*'",
			"package.json": JSON.stringify({}),
		});
		const pnpmRes = await detectCommands(pnpmMono);
		expect(pnpmRes.commands.map((c) => c.command)).toEqual(["pnpm -r --if-present test"]);
	});

	it("detects Go projects with go.mod", async () => {
		const r = await repo({ "go.mod": "module example.com/demo\ngo 1.22" });
		const res = await detectCommands(r);
		expect(res.runtime).toBe("go");
		expect(res.commands.map((c) => c.command)).toEqual(["go build ./...", "go test ./..."]);
	});

	it("detects Rust projects with Cargo.toml", async () => {
		const r = await repo({ "Cargo.toml": "[package]\nname = \"demo\"\nversion = \"0.1.0\"" });
		const res = await detectCommands(r);
		expect(res.runtime).toBe("rust");
		expect(res.commands.map((c) => c.command)).toEqual(["cargo build", "cargo test"]);
	});

	it("detects Deno projects with deno.json", async () => {
		const r = await repo({ "deno.json": "{ \"tasks\": { \"start\": \"deno run main.ts\" } }" });
		const res = await detectCommands(r);
		expect(res.runtime).toBe("deno");
		expect(res.commands.map((c) => c.command)).toEqual(["deno test"]);
	});

	it("detects Python projects across pyproject, setup.py, or requirements.txt", async () => {
		const py1 = await repo({ "pyproject.toml": "[tool.pytest.ini_options]\nminversion = '6.0'" });
		expect((await detectCommands(py1)).commands[0]?.command).toBe("pytest");

		const py2 = await repo({ "setup.py": "from setuptools import setup\nsetup()" });
		expect((await detectCommands(py2)).commands[0]?.command).toBe("pytest");

		const py3 = await repo({ "requirements.txt": "pytest>=7.0.0\nrequests" });
		expect((await detectCommands(py3)).commands[0]?.command).toBe("pytest");
	});

	it("detects Makefile targets when no other config matches", async () => {
		const r = await repo({
			Makefile: "typecheck:\n\ttsc\n\nbuild:\n\tmake\n\ntest:\n\tpytest\n",
		});
		const res = await detectCommands(r);
		expect(res.runtime).toBe("make");
		expect(res.commands.map((c) => c.command)).toEqual(["make typecheck", "make build", "make test"]);
	});

	it("prioritizes custom .kaioken/verify.json over auto-detected defaults", async () => {
		const r = await repo({
			"package.json": JSON.stringify({ scripts: { test: "jest" } }),
			".kaioken/verify.json": JSON.stringify({
				commands: [
					{ label: "custom-check", command: "./scripts/ci.sh", timeoutMs: 120000 },
				],
			}),
		});
		const res = await detectCommands(r);
		expect(res.source).toBe(VERIFY_CONFIG);
		expect(res.commands).toHaveLength(1);
		expect(res.commands[0]?.command).toBe("./scripts/ci.sh");
		expect(res.commands[0]?.timeoutMs).toBe(120000);
	});
});
